# This is a sample docker-compose.yml for our meteorjs webapp

version: '3' # STUB: obsolete warning, but required if still using ubuntu 22.04 host (not for 24.04)
services:
  docker-meteorjs-webapp:
    container_name: docker-meteorjs-webapp
    image: docker-meteorjs-webapp:latest
    restart: always    
    # STUB: use the host's network (e.g., Docker Desktop)
    # network_mode: "host" 
    ports:
      - '3000:3000'

# These are settings #1 for using ADDS Reverse Proxy
#     - '5020:3000'
#   networks: # Required section#1 for cp2/ to work via ADDNS Cname of cp2 to lm-docker01.lm.local. (with dot)
#     - proxy-network      

    volumes:
      - './webapp-meteor/:/app'        
      
# These are settings #2 for using ADDS Reverse Proxy
#networks: # Required section#2 for cp2/ to work via ADDNS Cname of cp2 to lm-docker01.lm.local. (with dot)
#  proxy-network:
#    external: true
